### ISSUE TITLE
Problems with use of pdp

### ISSUE THREAD

**Issue by aiqubo** [widdowquinn/find_differential_primers#53]
Dear developer,
I was installed pdp as  following step : 
## _1 ##
[aiqubo@aiqubo find_differential_primers]$ conda create --name pdp python=3.7
Proceed ([y]/n)? y
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
To activate this environment, use
conda activate pdp
To deactivate an active environment, use
conda deactivate
## _2 ##
(pdp) [aiqubo@aiqubo find_differential_primers]$ conda activate pdp
## _3 ##
(pdp) [aiqubo@aiqubo find_differential_primers]$ cd find_differential_primers/
## _4 ##
(pdp) [aiqubo@aiqubo find_differential_primers]$ conda install --file requirements.txt
Collecting package metadata (current_repodata.json): done
.......
Proceed ([y]/n)? y
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
## _5 ##
(pdp) [aiqubo@aiqubo find_differential_primers]$ conda install --file requirements-thirdparty-primer3_237.txt
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done
......
Proceed ([y]/n)? y
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
## _ 6##
(pdp) [aiqubo@aiqubo find_differential_primers]$ python setup.py install
/home/aiqubo/anaconda3/envs/pdp/lib/python3.7/site-packages/setuptools/dist.py:458: UserWarning: Normalizing '0.2.0.dev' to '0.2.0.dev0'
  warnings.warn(tmpl.format(**locals()))
running install
running bdist_egg
running egg_info
writing diagnostic_primers.egg-info/PKG-INFO
writing dependency_links to diagnostic_primers.egg-info/dependency_links.txt
writing entry points to diagnostic_primers.egg-info/entry_points.txt
writing requirements to diagnostic_primers.egg-info/requires.txt
writing top-level names to diagnostic_primers.egg-info/top_level.txt
reading manifest file 'diagnostic_primers.egg-info/SOURCES.txt'
writing manifest file 'diagnostic_primers.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
........
Using /home/aiqubo/anaconda3/envs/pdp/lib/python3.7/site-packages
Searching for numpy==1.19.2
Best match: numpy 1.19.2
Adding numpy 1.19.2 to easy-install.pth file
Installing f2py script to /home/aiqubo/anaconda3/envs/pdp/bin
Installing f2py3 script to /home/aiqubo/anaconda3/envs/pdp/bin
Installing f2py3.7 script to /home/aiqubo/anaconda3/envs/pdp/bin
Using /home/aiqubo/anaconda3/envs/pdp/lib/python3.7/site-packages
Searching for pytz==2020.4
Best match: pytz 2020.4
Adding pytz 2020.4 to easy-install.pth file
Using /home/aiqubo/anaconda3/envs/pdp/lib/python3.7/site-packages
Searching for python-dateutil==2.8.1
Best match: python-dateutil 2.8.1
Adding python-dateutil 2.8.1 to easy-install.pth file
Using /home/aiqubo/anaconda3/envs/pdp/lib/python3.7/site-packages
Finished processing dependencies for diagnostic-primers==0.2.0.dev0
(pdp) [aiqubo@aiqubo find_differential_primers]$ conda install -c bioconda biopython=1.77
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done
Package Plan
  environment location: /home/aiqubo/anaconda3/envs/pdp
  added / updated specs:
    - biopython=1.77
The following packages will be DOWNGRADED:
  biopython                             1.78-py37h8f50634_1 --> 1.77-py37h8f50634_1
Proceed ([y]/n)? y
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
## _7##
(pdp) [aiqubo@aiqubo find_differential_primers]$ pdp -help
Traceback (most recent call last):
  File "/home/aiqubo/anaconda3/envs/pdp/bin/pdp", line 33, in <module>
    sys.exit(load_entry_point('diagnostic-primers==0.2.0.dev0', 'console_scripts', 'pdp')())
  File "/home/aiqubo/anaconda3/envs/pdp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 488, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/aiqubo/anaconda3/envs/pdp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2872, in load_entry_point
    return ep.load()
  File "/home/aiqubo/anaconda3/envs/pdp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File "/home/aiqubo/anaconda3/envs/pdp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/aiqubo/anaconda3/envs/pdp/lib/python3.7/site-packages/diagnostic_primers-0.2.0.dev0-py3.7.egg/diagnostic_primers/scripts/pdp_script.py", line 48, in <module>
ImportError: cannot import name 'parsers' from 'diagnostic_primers.scripts'(/home/aiqubo/anaconda3/envs/pdp/lib/python3.7/site-packages/diagnostic_primers-0.2.0.dev0-py3.7.egg/diagnostic_primers/scripts/__init__.py)

is something wrong?

qubo

**Comment by widdowquinn** [comment]
Hi @aiqubo - thank you for your interest in `pdp`.

I don't see from your issue how you acquired `pdp`. Did you clone the repository? If so, what is the most recent commit in your version of the repository (you can discover this with the command `git log`).

Please note that `pdp` is the development branch and should not be considered to be stable. The stable version (which should be installable using `conda install -c bioconda find_differential_primers`, see [https://github.com/widdowquinn/find_differential_primers/tree/master](https://github.com/widdowquinn/find_differential_primers/tree/master)) may be more reliable for you.

L.

**Comment by aiqubo** [comment]
Hi Leighton - thank you for feedback,
I'm more interested in the new version
I download  pdp use 'git clone https://github.com/widdowquinn/find_differential_primers'

qubo

**Comment by widdowquinn** [comment]
> Hi Leighton - thank you for feedback,
> I'm more interested in the new version
> I download pdp use 'git clone https://github.com/widdowquinn/find_differential_primers'
> 
> qubo

Apologies for the delayed response - I missed your reply.

Please could you try installing in a clean environment with:

```bash
conda install --file requirements.txt -y
conda install --file requirements-thirdparty-primer3_237.txt -y
pip install -e .
```

and then try `pdp -h`?

**Comment by davidjstudholme** [comment]
I'm not sure whether @aiqubo experiences the same, but it might be relevant that the above commands fail because the packages are not found in the conda repos:

`conda install --file requirements.txt -y` gives:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pybedtools

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
And `conda install --file requirements-thirdparty-primer3_237.txt -y` gives: 

```
PackagesNotFoundError: The following packages are not available from current channels:

  - mafft
  - mummer==3.23
  - bedtools
  - primer3==2.3.7

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
```

`git log` gives:

```
commit 54e4fb3d63d2610559d93249a5e389dad1caed90 (HEAD -> diagnostic_primers, origin/diagnostic_primers, origin/HEAD)
Merge: 3e3863d cb830b4
Author: Leighton Pritchard <leightonpritchard@mac.com>
Date:   Fri Dec 18 14:20:49 2020 +0000

```
