### ISSUE TITLE
parameter defaults

### ISSUE THREAD

**Issue by nick-youngblut** [widdowquinn/find_differential_primers#55]
It would be helpful to include defaults for each subcommand. For instance:

```
$ pdp eprimer3 -h
usage: pdp.py eprimer3 [-h] [-l LOGFILE] [-v] [--disable_tqdm] [-s SCHEDULER]
                       [-w WORKERS] [--SGEgroupsize SGEGROUPSIZE]
                       [--SGEargs SGEARGS] [--jobprefix JOBPREFIX]
                       [--recovery] [--eprimer3 EPRIMER3_EXE]
                       [--outdir EPRIMER3_DIR] [-f] [--filter]
                       [--numreturn EP_NUMRETURN] [--osize EP_OSIZE]
                       [--minsize EP_MINSIZE] [--maxsize EP_MAXSIZE]
                       [--opttm EP_OPTTM] [--mintm EP_MINTM]
                       [--maxtm EP_MAXTM] [--ogcpercent EP_OGCPERCENT]
                       [--mingcpercent EP_MINGC] [--maxgcpercent EP_MAXGC]
                       [--psizeopt EP_PSIZEOPT] [--psizemin EP_PSIZEMIN]
                       [--psizemax EP_PSIZEMAX] [--maxpolyx EP_MAXPOLYX]
                       [--hybridprobe] [--oligoosize EP_OSIZEOPT]
                       [--oligominsize EP_OMINSIZE]
                       [--oligomaxsize EP_OMAXSIZE] [--oligootm EP_OTMOPT]
                       [--oligomintm EP_OTMMIN] [--oligomaxtm EP_OTMMAX]
                       [--oligoogcpercent EP_OGCOPT]
                       [--oligomingcpercent EP_OGCMIN]
                       [--oligomaxgcpercent EP_OGCMAX]
                       infilename outfilename

positional arguments:
  infilename            path to configuration file
  outfilename           Path to write new configuration file

optional arguments:
  -h, --help            show this help message and exit
  -l LOGFILE, --logfile LOGFILE
                        logfile location
  -v, --verbose         report progress to log
  --disable_tqdm        turn off tqdm progress bar
  -s SCHEDULER, --scheduler SCHEDULER
                        Job scheduler [multiprocessing|SGE]
  -w WORKERS, --workers WORKERS
                        Number of parallel workers to use
  --SGEgroupsize SGEGROUPSIZE
                        Number of jobs to place in an SGE array group (default
                        10000)
  --SGEargs SGEARGS     Additional arguments for qsub
  --jobprefix JOBPREFIX
                        prefix for scheduled jobs
  --recovery            skip scheduled third-party tool calls and reuse output
  --eprimer3 EPRIMER3_EXE
                        path to ePrimer3 executable
  --outdir EPRIMER3_DIR
                        path to directory for ePrimer3 output
  -f, --force           Overwrite old ePrimer3 output
  --filter              use the filtered_seqfile to design primer sets
  --numreturn EP_NUMRETURN
                        number of primers to return
  --osize EP_OSIZE      optimal size for primer oligo
  --minsize EP_MINSIZE  minimum size for primer oligo
  --maxsize EP_MAXSIZE  maximum size for primer oligo
  --opttm EP_OPTTM      optimal Tm for primer oligo
  --mintm EP_MINTM      minimum Tm for primer oligo
  --maxtm EP_MAXTM      maximum Tm for primer oligo
  --ogcpercent EP_OGCPERCENT
                        optimal %GC for primer oligo
  --mingcpercent EP_MINGC
                        minimum %GC for primer oligo
  --maxgcpercent EP_MAXGC
                        maximum %GC for primer oligo
  --psizeopt EP_PSIZEOPT
                        optimal size of amplified region
  --psizemin EP_PSIZEMIN
                        minimum size of amplified region
  --psizemax EP_PSIZEMAX
                        maximum size of amplified region
  --maxpolyx EP_MAXPOLYX
                        maximum run of repeated nucleotides in primer
  --hybridprobe         design a reporter oligo
  --oligoosize EP_OSIZEOPT
                        optimal size for internal oligo
  --oligominsize EP_OMINSIZE
                        minimum size for internal oligo
  --oligomaxsize EP_OMAXSIZE
                        maximum size for internal oligo
  --oligootm EP_OTMOPT  optimal Tm for internal oligo
  --oligomintm EP_OTMMIN
                        minimum Tm for internal oligo
  --oligomaxtm EP_OTMMAX
                        maximum Tm for internal oligo
  --oligoogcpercent EP_OGCOPT
                        optimal %GC for internal oligo
  --oligomingcpercent EP_OGCMIN
                        minimum %GC for internal oligo
  --oligomaxgcpercent EP_OGCMAX
                        maximum %GC for internal oligo
```
...it's not clear what any of the defaults are. For argparse, the defaults can all be easily displayed via:

```
parser = argparse.ArgumentParser( # ... other options ... formatter_class=argparse.ArgumentDefaultsHelpFormatter)
```

**Comment by nick-youngblut** [comment]
One reason why I'm posting this feature request is that in your walkthrough, `pdp eprimer3 --filter --outdir tests/walkthrough/eprimer3  tests/walkthrough/fixed_with_features.json  tests/walkthrough/with_primers.json` doesn't generate any primers with the default parameters, so I was going to find parameters that actually worked, but running `pdp eprimer3` didn't help with determining the defaults. 

Any idea what parameter settings with generate parameters for `pdp eprimer3` in the walkthrough? 

I'm really surprised that NO primers could be generated from any of the 3 example genomes when using the default parameters. Are the defaults too strict?

**Comment by nick-youngblut** [comment]
It appears that the walkthrough cannot be completed due to the lack of primers found by `pdp eprimer3`:

```
$ pdp classify \
>        tests/walkthrough/primersearch.json \
>        tests/walkthrough/classify
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/primers/bin/pdp", line 33, in <module>
    sys.exit(load_entry_point('diagnostic-primers', 'console_scripts', 'pdp')())
  File "/ebio/abt3_projects/software/dev/tmp/primer_design/find_differential_primers/diagnostic_primers/scripts/pdp_script.py", line 71, in run_pdp_main
    returnval = args.func(args, logger)
  File "/ebio/abt3_projects/software/dev/tmp/primer_design/find_differential_primers/diagnostic_primers/scripts/subcommands/subcmd_classify.py", line 84, in subcmd_classify
    ampset.from_json(dataset.target_amplicons)
  File "/ebio/abt3_projects/software/dev/tmp/primer_design/find_differential_primers/diagnostic_primers/primersearch.py", line 285, in from_json
    with open(filename, "r") as ifh:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

```
$ cat tests/walkthrough/primersearch.json
[{"features": "tests/walkthrough/prodigal/GCF_000011605.1.gff", "filestem": "GCF_000011605.1", "filtered_seqfile": "tests/walkthrough/prodigal/GCF_000011605.1_filtered.fasta", "groups": ["Pectobacterium", "atrosepticum_NCBI", "gv1"], "name": "Pba_SCRI1043", "primers": "tests/walkthrough/deduped/GCF_000011605.1_named_deduped_screened.json", "primersearch": "tests/walkthrough/primersearch/Pba_SCRI1043_primersearch.json", "seqfile": "tests/walkthrough/sequences/GCF_000011605.1.fasta", "target_amplicons": null}, {"features": "tests/walkthrough/prodigal/GCF_000749845.1_concat.gff", "filestem": "GCF_000749845.1_concat", "filtered_seqfile": "tests/walkthrough/prodigal/GCF_000749845.1_concat_filtered.fas", "groups": ["Pectobacterium", "betavasculorum_NCBI", "gv7"], "name": "Pbe_NCPPB_2795", "primers": "tests/walkthrough/deduped/GCF_000749845.1_concat_named_deduped_screened.json", "primersearch": "tests/walkthrough/primersearch/Pbe_NCPPB_2795_primersearch.json", "seqfile": "GCF_000749845.1_concat.fas", "target_amplicons": null}, {"features": "tests/walkthrough/prodigal/GCF_000291725.1_concat_noambig.gff", "filestem": "GCF_000291725.1_concat_noambig", "filtered_seqfile": "tests/walkthrough/prodigal/GCF_000291725.1_concat_noambig_filtered.fas", "groups": ["Pectobacterium", "gv2", "wasabiae_NCBI"], "name": "Pwa_CFBP_3304", "primers": "tests/walkthrough/deduped/GCF_000291725.1_concat_noambig_named_deduped_screened.json", "primersearch": "tests/walkthrough/primersearch/Pwa_CFBP_3304_primersearch.json", "seqfile": "GCF_000291725.1_concat_noambig.fas", "target_amplicons": null}]
```

**Comment by widdowquinn** [comment]
>  For argparse, the defaults can all be easily displayed via:
> 
> ```
> parser = argparse.ArgumentParser( # ... other options ... formatter_class=argparse.ArgumentDefaultsHelpFormatter)
> ```

That is true - would you like to make a pull request with that change?

**Comment by widdowquinn** [comment]
> One reason why I'm posting this feature request is that in your walkthrough, `pdp eprimer3 --filter --outdir tests/walkthrough/eprimer3 tests/walkthrough/fixed_with_features.json tests/walkthrough/with_primers.json` doesn't generate any primers with the default parameters, so I was going to find parameters that actually worked, but running `pdp eprimer3` didn't help with determining the defaults.
> 
> Any idea what parameter settings with generate parameters for `pdp eprimer3` in the walkthrough?
> 
> I'm really surprised that NO primers could be generated from any of the 3 example genomes when using the default parameters. Are the defaults too strict?

I'm surprised, too.  Here's what I get:

```bash
(pdp_38) [19:03:46] lpritc@Gyaos:find_differential_primers$ ls tests/walkthrough/sequences/
GCF_000011605.1.fasta  GCF_000291725.1.fasta  GCF_000749845.1.fasta
(pdp_38) [19:04:08] lpritc@Gyaos:find_differential_primers$ pdp config --validate tests/walkthrough/pectoconf.tab
identifying validation problems: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  5.75it/s]
WARNING: Validation problems
    Pbe_NCPPB_2795 requires stitch (tests/walkthrough/sequences/GCF_000749845.1.fasta)
    Pwa_CFBP_3304 requires stitch (tests/walkthrough/sequences/GCF_000291725.1.fasta)
    Pwa_CFBP_3304 has non-N ambiguities (tests/walkthrough/sequences/GCF_000291725.1.fasta)
(pdp_38) [19:04:16] lpritc@Gyaos:find_differential_primers$ pdp config --fix_sequences tests/walkthrough/fixed.json \
>                 tests/walkthrough/pectoconf.tab
identifying validation problems: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  3.06it/s]
(pdp_38) [19:04:27] lpritc@Gyaos:find_differential_primers$ pdp filter --prodigal --outdir tests/walkthrough/prodigal \
>                 tests/walkthrough/fixed.json \
>                 tests/walkthrough/fixed_with_features.json
collecting prodigal output: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 21435.97it/s]
compiling filtered genomes: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 32939.56it/s]
(pdp_38) [19:05:04] lpritc@Gyaos:find_differential_primers$ pdp eprimer3 --filter --outdir tests/walkthrough/eprimer3 \
>                   tests/walkthrough/fixed_with_features.json \
>                   tests/walkthrough/with_primers.json
Writing: tests/walkthrough/eprimer3/GCF_000291725.1_concat_noambig_named.bed: 100%|█████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  6.93it/s]
```

and this does seem to generate primers:

```bash
(pdp_38) [19:07:18] lpritc@Gyaos:find_differential_primers$ ls -l tests/walkthrough/eprimer3/
total 120
-rw-r--r--  1 lpritc  staff   1.7K 17 Dec 19:05 GCF_000011605.1.eprimer3
-rw-r--r--  1 lpritc  staff   722B 17 Dec 19:06 GCF_000011605.1_named.bed
-rw-r--r--  1 lpritc  staff   2.6K 17 Dec 19:06 GCF_000011605.1_named.eprimer3
-rw-r--r--  1 lpritc  staff   4.9K 17 Dec 19:06 GCF_000011605.1_named.json
-rw-r--r--  1 lpritc  staff   1.7K 17 Dec 19:06 GCF_000291725.1_concat_noambig.eprimer3
-rw-r--r--  1 lpritc  staff   948B 17 Dec 19:06 GCF_000291725.1_concat_noambig_named.bed
-rw-r--r--  1 lpritc  staff   2.7K 17 Dec 19:06 GCF_000291725.1_concat_noambig_named.eprimer3
-rw-r--r--  1 lpritc  staff   5.0K 17 Dec 19:06 GCF_000291725.1_concat_noambig_named.json
-rw-r--r--  1 lpritc  staff   1.7K 17 Dec 19:05 GCF_000749845.1_concat.eprimer3
-rw-r--r--  1 lpritc  staff   792B 17 Dec 19:06 GCF_000749845.1_concat_named.bed
-rw-r--r--  1 lpritc  staff   2.7K 17 Dec 19:06 GCF_000749845.1_concat_named.eprimer3
-rw-r--r--  1 lpritc  staff   4.8K 17 Dec 19:06 GCF_000749845.1_concat_named.json
(pdp_38) [19:07:24] lpritc@Gyaos:find_differential_primers$ head tests/walkthrough/eprimer3/GCF_000011605.1.eprimer3 

# EPRIMER3 RESULTS FOR _filtered

#                      Start  Len   Tm     GC%   Sequence

   1 PRODUCT SIZE: 100
     FORWARD PRIMER  1252579   20  59.01  50.00  GATAAACCTGCCGATCTGGT

     REVERSE PRIMER  1252659   20  59.00  45.00  GAATTTCTGCAACAGGCTCA
```

I am afraid I am unable to reproduce your failure to generate primers with this command. I also found that executing the `walkthrough.sh` script generated the expected result for all of the runs.

Please could I ask you to verify that you have installed `pdp` in its own (clean) environment, and also to confirm which version of ePrimer3 you are using? You might consider including a logfile generated during your run (or with the `-v` option) to aid with diagnosis. This will contain all the commands submitted to `eprimer3` or `primer3` (depending which you have available).

L.

**Comment by nick-youngblut** [comment]
It might be due to the software versions that you're using versus me. My conda env:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
astroid                   2.4.2            py37hc8dfbb8_1    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
bandit                    1.6.2            py37hc8dfbb8_2    conda-forge
bedtools                  2.29.2               hc088bd4_0    bioconda
biopython                 1.77             py37h8f50634_1    conda-forge
black                     20.8b1                     py_1    conda-forge
blacken-docs              1.8.0                    pypi_0    pypi
blast                     2.10.1          pl526he19e7b1_3    bioconda
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.8            h06a4308_0
certifi                   2020.12.5        py37h89c1867_0    conda-forge
cfgv                      3.2.0                    pypi_0    pypi
chardet                   4.0.0                    pypi_0    pypi
click                     7.1.2              pyh9f0ad1d_0    conda-forge
codecov                   2.1.10                   pypi_0    pypi
coverage                  5.3              py37h8f50634_1    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
dataclasses               0.7                      py37_0    conda-forge
diagnostic-primers        0.2.0.dev0                dev_0    <develop>
distlib                   0.3.1                    pypi_0    pypi
emboss                    6.6.0                hf7d6862_3    bioconda
entrez-direct             13.9            pl526h375a9b1_0    bioconda
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.2.10               he6710b0_2
filelock                  3.0.12                   pypi_0    pypi
flake8                    3.8.4                      py_0    conda-forge
fontconfig                2.13.1            h1056068_1002    conda-forge
freetype                  2.10.4               he06d7ca_0    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
gitdb                     4.0.5                      py_0    conda-forge
gitpython                 3.1.11                     py_0    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
identify                  1.5.10                   pypi_0    pypi
idna                      2.10                     pypi_0    pypi
importlib-metadata        3.3.0            py37h89c1867_2    conda-forge
importlib_metadata        3.3.0                hd8ed1ab_2    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
isort                     5.6.4                      py_0    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    1.0.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lazy-object-proxy         1.4.3            py37h8f50634_2    conda-forge
ld_impl_linux-64          2.35.1               hed1e6ac_1    conda-forge
libblas                   3.9.0                3_openblas    conda-forge
libcblas                  3.9.0                3_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgd                     2.2.5             h341251c_1008    conda-forge
libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
libgfortran4              7.5.0               hae1eefd_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                3_openblas    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.1.0                h56121f0_4    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
mafft                     7.475                h516909a_0    bioconda
markupsafe                1.1.1            py37hb5d75c8_2    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
more-itertools            8.6.0              pyhd8ed1ab_0    conda-forge
mummer                    3.23            pl526he1b5a44_11    bioconda
mypy_extensions           0.4.3            py37hc8dfbb8_2    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nodeenv                   1.5.0                    pypi_0    pypi
numpy                     1.19.4           py37haa41c4c_2    conda-forge
openpyxl                  3.0.5                      py_0    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
packaging                 20.8               pyhd3deb0d_0    conda-forge
pandas                    1.1.5            py37hdc94413_0    conda-forge
pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
pbr                       5.5.1              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-archive-tar          2.32                    pl526_0    bioconda
perl-base                 2.23                    pl526_1    bioconda
perl-business-isbn        3.004                   pl526_0    bioconda
perl-business-isbn-data   20140910.003            pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-data-dumper          2.173                   pl526_0    bioconda
perl-digest-hmac          1.03                    pl526_3    bioconda
perl-digest-md5           2.55                    pl526_0    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-encode-locale        1.05                    pl526_6    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-listing         6.04                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-html-parser          3.72            pl526h6bb024c_5    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-html-tree            5.07                    pl526_1    bioconda
perl-http-cookies         6.04                    pl526_0    bioconda
perl-http-daemon          6.01                    pl526_1    bioconda
perl-http-date            6.02                    pl526_3    bioconda
perl-http-message         6.18                    pl526_0    bioconda
perl-http-negotiate       6.01                    pl526_3    bioconda
perl-io-compress          2.087           pl526he1b5a44_0    bioconda
perl-io-html              1.001                   pl526_2    bioconda
perl-io-socket-ssl        2.066                   pl526_0    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-libwww-perl          6.39                    pl526_0    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-lwp-mediatypes       6.04                    pl526_0    bioconda
perl-lwp-protocol-https   6.07                    pl526_4    bioconda
perl-mime-base64          3.15                    pl526_1    bioconda
perl-mozilla-ca           20180117                pl526_1    bioconda
perl-net-http             6.19                    pl526_0    bioconda
perl-net-ssleay           1.88            pl526h90d6eec_0    bioconda
perl-ntlm                 1.09                    pl526_4    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-socket               2.027                   pl526_1    bioconda
perl-storable             3.15            pl526h14c3975_0    bioconda
perl-test-requiresinternet 0.05                    pl526_0    bioconda
perl-time-local           1.28                    pl526_1    bioconda
perl-try-tiny             0.30                    pl526_1    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-uri                  1.76                    pl526_0    bioconda
perl-www-robotrules       6.02                    pl526_3    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44_01         pl526ha1d75be_1002    conda-forge
perl-xml-sax              1.02                    pl526_0    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_3    bioconda
perl-xml-simple           2.25                    pl526_1    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
plotly                    4.14.1                   pypi_0    pypi
pluggy                    0.13.1           py37he5f6b98_3    conda-forge
pre-commit                2.9.3                    pypi_0    pypi
primer3                   2.3.7           pl526hfc679d8_1    bioconda
prodigal                  2.6.3                h516909a_2    bioconda
py                        1.10.0             pyhd3deb0d_0    conda-forge
pybedtools                0.8.1            py37h8270d21_2    bioconda
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pylint                    2.6.0            py37hc8dfbb8_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysam                     0.16.0.1         py37hc334e0b_1    bioconda
pytest                    6.2.1            py37h89c1867_0    conda-forge
pytest-cov                2.10.1             pyh9f0ad1d_0    conda-forge
python                    3.7.9           hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.4             pyhd8ed1ab_0    conda-forge
pyyaml                    5.3.1            py37hb5d75c8_1    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
regex                     2020.11.13       py37h4abf009_0    conda-forge
requests                  2.25.1                   pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
setuptools                51.0.0           py37h06a4308_2
six                       1.15.0             pyh9f0ad1d_0    conda-forge
smmap                     3.0.4              pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
stevedore                 3.3.0            py37h89c1867_0    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tqdm                      4.54.1             pyhd8ed1ab_0    conda-forge
typed-ast                 1.4.1            py37h4abf009_1    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.26.2                   pypi_0    pypi
virtualenv                20.2.2                   pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wrapt                     1.11.2           py37h8f50634_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
```

Which version of EMBOSS are you using?

**Comment by widdowquinn** [comment]
> It might be due to the software versions that you're using versus me. My conda env:

That may well be the case.

> Which version of EMBOSS are you using?

```bash
$ conda list | grep emboss
emboss                    6.6.0                h6debe1e_0    bioconda
```

Please could I ask you again to verify that you have installed pdp in its own (clean) environment, and also to confirm which version of primer3 you are using (v1 or v2)? You might consider including a logfile generated during your run (or with the -v option) to aid with diagnosis. This will contain all the commands submitted to eprimer3 or primer3 (depending which you have available), and you can then test those individually to see if they generate output.

**Comment by nick-youngblut** [comment]
I'm using `primer3     2.3.7   pl526hfc679d8_1    bioconda`.

I used the setup as shown in your .travis.yml to create the conda env and install pdp.

**Comment by widdowquinn** [comment]
Thank you for answering the question about which version of `primer3` you are using. This explains why you are seeing no primer output.

The command `pdp eprimer3` uses the EMBOSS interface, which works only for `primer3` version 1. If you want to use `pdp eprimer3` as in the walkthrough then you will need to install the older version of `primer3`. Please examine the two `requirements-thirdparty*` files to see how I install the different versions using `conda`.

If you would like to use the more modern `primer3` version 2, you cannot use the EMBOSS interface; this is a limitation of EMBOSS (they did not track the `primer3` CLI). You will instead have to use the `pdp primer3` subcommand. Please do keep in mind that this is an alpha version of `pdp` that is under development and this subcommand has not yet been documented, so my strong recommendation is that you install the earlier `primer3` and use the EMBOSS interface.

L.

**Comment by widdowquinn** [comment]
In case you're interested, a comparable path through the workflow is:

```bash
OUTDIR=tests/walkthrough
pdp config --validate ${OUTDIR}/pectoconf.tab
pdp config --fix_sequences ${OUTDIR}/fixed.json \
    --outdir ${OUTDIR}/config \
    ${OUTDIR}/pectoconf.tab
pdp primer3 \
    --outdir ${OUTDIR}/eprimer3 \
    --therm_param_path tests/test_input/primer3/primer3_config \  # NOTE THERMODYNAMIC PARAMETERS
    ${OUTDIR}/fixed.json \
    ${OUTDIR}/with_primers.json
pdp dedupe -f \
    --dedupedir ${OUTDIR}/deduped \
    ${OUTDIR}/with_primers.json \
    ${OUTDIR}/deduped_primers.json
pdp blastscreen -f \
    --db ${OUTDIR}/blastdb/e_coli_screen.fna \
    --outdir ${OUTDIR}/blastn \
    ${OUTDIR}/deduped_primers.json \
    ${OUTDIR}/screened.json
pdp primersearch -f \
    --outdir ${OUTDIR}/primersearch \
    ${OUTDIR}/screened.json \
    ${OUTDIR}/primersearch.json
pdp classify -f \
    ${OUTDIR}/primersearch.json \
    ${OUTDIR}/classify
pdp extract -f \
    ${OUTDIR}/primersearch.json \
    ${OUTDIR}/classify/atrosepticum_NCBI_primers.json \
    ${OUTDIR}/extract
```

**Comment by widdowquinn** [comment]
As you cannot have both versions of `primer3` in the `$PATH` at once (the `primer3_core` executables conflict) you may find it helpful to maintain separate environments for each `primer3` version.

**Comment by nick-youngblut** [comment]
Yeah, using `primer3=1.1.4` fixed the issue. I didn't have 2 versions of primer3 in my PATH. I'm guessing that `primer3=2.3.7` just doesn't produce any primers for the tutorial genomes with defaults set in `pdp eprimer3`. It might be helpful to include the entire tutorial in your CI tests (they don't appear to be in your current tests, based on a quick check). I've found https://pypi.org/project/pytest-console-scripts/ to be very helpful for such CLI tests.

**Comment by widdowquinn** [comment]
> Yeah, using `primer3=1.1.4` fixed the issue. I didn't have 2 versions of primer3 in my PATH. I'm guessing that `primer3=2.3.7` just doesn't produce any primers for the tutorial genomes with defaults set in `pdp eprimer3`.

As explained above, `pdp eprimer3` **only** works with `primer3` version 1. You would need to use `pdp primer3` instead.

> It might be helpful to include the entire tutorial in your CI tests (they don't appear to be in your current tests, based on a quick check). I've found https://pypi.org/project/pytest-console-scripts/ to be very helpful for such CLI tests.

Yes, confirming that the tutorial commands work in CI is my usual practice. As noted previously, this is a development version, and incomplete: not everything is done, yet (including a planned move away from TravisCI).

**Comment by nick-youngblut** [comment]
> including a planned move away from TravisCI

Something like the following should work for switching to github CI:

```
name: find_differential_primers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        python-version: [3.6, 3.7]
        primer3-version: [1.1.4, 2.3.7]
    steps:
    - uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: 'latest'
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,bioconda
        activate-environment: find_differential_primers
    - name: conda env setup
      shell: bash -l {0}
      run: |
        pwd
        conda info -a
        conda install python=${{ matrix.python-version }} prodigal blast bedtools mafft mummer=3.23 emboss primer3=${{ matrix.primer3-version }}
        conda install  --yes --file requirements.txt
        conda install --yes --file requirements-dev.txt
        pip install -r requirements-pip.txt
    - uses: actions/checkout@v2	
    - name: package install
      shell: bash -l {0}
      run: |
        pip install -e .
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest -s -v --cov=./
```
